print("Hello. I am a demo version of a new chat program. My name is Chat0.")
name = input("What is your name?:")
print("Nice to meet you", name)
situation = input("How are you?")
print("I hope you will be better.", name)
language = input("How many languages do you know besides your mother tongue?")
print(language, "This is very good. You have to keep improving yourself. Every language is a person.")
busy = input("What are you busy with these days?")
print(busy,"It supposed to be very important to you.")
book = input("How many pages of books do you read daily?")
print(book,"The number of pages is not matters. Continuity and effectiveness reading is more valuable.")
food = input("What is your favoriet food?")
print("Delicious.")